### ISSUE TITLE
Doesn't work with ST3210 ?

### ISSUE THREAD

**Issue by themilkman** [jakebathman/nginx-log-highlighting#2]
Hi @jakebathman, I just gave your plugin a try and it doesn't work at all for me. 
I use version 3210 of ST. Of course, I tried restarting. I don't see any errors on my ST console.

Is it only for me? Or may someone confirm it?

All parts (tried your example, too) is only interpreted as "text.nginx", thus there are no colors.

Thanks for any feedback, cheers!

**Comment by jakebathman** [comment]
Nuts, let me see if I can figure out what's going wrong. I don't use ST day-to-day anymore but don't want to leave anyone hanging.

**Comment by themilkman** [comment]
Thank you very much for your light speed action! :pray: 
The latest version works fine here.
